### ISSUE TITLE
Tracking testing results for encryption

### ISSUE THREAD

**Issue by davitol** [owncloud/encryption#142]
[WIP]

Tested in oC 10.3 and encryption 1.4.0. RC1

### CLI commands for encryption
 - [x] encryption:change-key-storage-root  Change key storage root.
 - [x]  encryption:decrypt-all              Disable server-side encryption and decrypt all files.
 - [x] encryption:disable                  Disable encryption.
 - [x]  encryption:enable                   Enable encryption.
  - [x] encryption:encrypt-all              Encrypt all files for all users.
 - [x]  encryption:fix-encrypted-version    Fix the encrypted version if the encrypted file(s) are not downloadable.
  - [ ] encryption:hsmdaemon                hsmdaemon tool
  - [x] encryption:list-modules             List all available encryption modules.
  - [x] encryption:migrate                  initial migration to encryption 2.0
  - [x] encryption:recreate-master-key      Replace existing master key with new one. Encrypt the file system with newly created master key
  - [x] encryption:select-encryption-type   Select the encryption type. The encryption types available are: masterkey and user-keys. There is also no way to disable it again.
  - [x] encryption:set-default-module       Set the encryption default module.
  - [x] encryption:show-key-storage-root    Show current key storage root.
  - [x] encryption:status                   Lists the current encryption status.

### Encryption via WebUI
 - [x] Enable Default encryption module  app
 - [x] Disable Default encryption module  app
 - [x] Enable server-side encryption
 - [x] Enable Default encryption module with Master Key
 - [x] Enable Default encryption module with User Keys
 - [x] Enable password recovery
