### ISSUE TITLE
[strictly 10.7.0] Release Encryption 1.5.0

### ISSUE THREAD

**Issue by phil-davis** [owncloud/encryption#220]
## Reason

PR #218 "add path option to FixEncryptedVersion command" was merged.
(and whatever else has been added to `master` since 1.4.0)

### Product approval 

- [ ] Verify transifex commits are in master: If a folder https://github.com/owncloud/<APPNAME>/tree/master/l10n exists, then https://drone.owncloud.com/owncloud/<APPNAME> should receive nightly '[tx] updated from transifex` ...
- [ ] Ping pmaier to check `info.xml` description and screenshot
- [ ] Get approval on translations from pmaier - send the date of the last tx commit from drone to Patrick

### QA

- [x] Generate Changelog
- [x] Create **QA** Milestone and set the description to $version
- [ ] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "$version Testplan" ([QA templates](https://github.com/owncloud/QA/tree/master/Server)) -> see below https://github.com/owncloud/encryption/issues/220#issuecomment-797105412
- [ ] copy new/reopened issues from the previous release ticket as 'Issues to review' below.

### Documentation

- [ ] Changes in the docs needed? If so create issue in owncloud/docs.

### Marketing

- [ ] Ping @owncloud/marketing

### Build

All actions to be done on the release branch from here:
- [x] Bump version in `info.xml` (no version suffix)
- [x] Check php version dependency in `info.xml`
- [x] Check minimum ownCloud version dependency in `info.xml`
- [x] Change CHANGELOG.md 'Unreleased' to '$version' (today's date)

#### Beta/RC

- [x] Create github tag for `v${version}RC1` on release branch
- [x] Build and sign RC tarball from github tag `v${version}RC1` (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Manual explorative testing:
    - [x] If this is an enterprise app: Enabling the app must start the grace period.
    - [x] Changelog testing
    - [x] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [ ] Check that no documentation issues are pending
- [x] Rename last RC tarball to final
- [x] Create github tag for final `v${version}` on release branch
- [x] Upload as Github release using changelog entries
- [ ] Ping `#marketing` channel to coordinate publishing

### Publishing
Not done. Encrytion is special.

- [ ] ~Upload tarball to marketplace (see handbook in confluence for details)~
- [ ] ~Publish tarball for customers (see handbook in confluence for details) - https://customer.owncloud.com and https://portal.owncloud.com~
- [ ] ~Send mail to release-coordination with link to this ticket and to the changelog~
- [ ] ~Copy email to rocket chat `#updates` channel~

### Post-release

- [x] Rename QA milestone to `$version`
- [x] Add a new 'Unreleased' section in CHANGELOG.md (and also update links at the bottom!)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number
- [x] Close the milestone
- [x] Ensure [release template](https://github.com/owncloud/administration-internal/edit/master/tools/release/templates/server_app_release_template.md) is up to date

**Comment by JanAckermann** [comment]
https://github.com/owncloud/encryption/pull/226 (Open)

**Comment by cdamken** [comment]
Could this be added into the 10.6.1? @micbar

**Comment by phil-davis** [comment]
And PR #25 has been merged.
Note: that depends on core PR https://github.com/owncloud/core/pull/38289 which will be in the next core release after 10.6.0 (probably will be numbered 10.7.0) So the core min-version for this encryption app should be bumped when releasing. See comments in issue #229 for more information.

**Comment by phil-davis** [comment]
And #224 is ready to merge. That also will not play nicely with core 10.6.0 - so releasing encryption will need a core release first.

**Comment by micbar** [comment]
@enbrnz do we need a encryption release before 10.7.0 ?

**Comment by enbrnz** [comment]
Well depends on when 10.7.0 is being released?

In the meantime I can try to figure out whether any customers are waiting for a fix for this. Unfortunately this is very hard, as the issue is not linking back to any customer issues...

**Comment by jnweiger** [comment]
That gets tricky?
* encryption app requires server 10.7 with https://github.com/owncloud/core/pull/38452
* https://github.com/owncloud/enterprise/issues/4276 in server 10.7 requires a release of encryption app?

So should we build and test both together to make it a release?

**Comment by jnweiger** [comment]
## Testplan Encryption 1.5.0

### Setup

* [ ] install on 10.7.0 test systems
     - [ ] https://135.181.204.143/owncloud
     - [ ] https://135.181.107.50/owncloud
     - [ ] https://oc-10-7-0-beta2.oidc-2-0-0-20210311.jw-qa.owncloud.works

### Test items (Changelog testing)

* [ ] Add path option to FixEncryptedVersion command - #218
* [ ] Make encryption repair for file and folder [#4276](https://github.com/owncloud/enterprise/issues/4276)
* [ ] Use PHP's built-in hash_hkdf function [#215](https://github.com/owncloud/encryption/pull/215)
* [ ] Unnecessary file size overhead (binary instead of base64) [#210](https://github.com/owncloud/encryption/issues/210)
* [ ] Code needs updating due to core icewind/streams 0.7.2 [#198](https://github.com/owncloud/encryption/issues/198)

**Comment by jnweiger** [comment]
## Issues opened while testing

* [ ] #250 encryption app should be named just Encryption
